### PR TITLE
Test on node 14

### PR DESCRIPTION
**Pull request by geek**

### CODE REVIEW

**Comment by cjihrig** [comment]
Can you update this to use the Travis templates?

**Comment by geek** [comment]
@cjihrig updated

**Comment by Marsup** [comment]
The test that's failing seems flaky, it works most of the time locally but I managed to make it fail, probably increase the wait a little bit ?

**Comment by cjihrig** [comment]
I cleared the Travis cache and restarted the CI, and now everything is green.

**Comment by Marsup** [comment]
It still fails sometimes locally, so I'd expect some errors every once in a while.

**Comment by cjihrig** [comment]
Yes, we should still try to fix the flaky test.

**Pull request merged**
